### ISSUE TITLE
Cannot find the object "dbo.MonitoredRoutes" because it does not exist

### ISSUE THREAD

**Issue by abdale** [Azure-Samples/azure-sql-db-serverless-geospatial-stream-analytics#1]
Hello,

When running the [sql script](https://github.com/Azure-Samples/azure-sql-db-serverless-geospatial-stream-analytics/blob/fd8652565e9770de5b2c466f701224aa33ce40b6/sql/00-create-objects.sql#L44) to create the tables, it seems like the table dbo.MonitoredRoutes is not being created before it is altered.

Thanks.

**Comment by attrib75** [comment]
+1
